//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSakurso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Birth_Date { get; set; }
        public string Phone { get; set; }
        public string Doctor { get; set; }
        public string Appointment_Date { get; set; }
        public int Personal_No { get; set; }
        public string Appointment_Time { get; set; }
    }
}
